### PR TITLE
Enumerated sets: emacs reminders, extra obvious exercises.

### PR DESCRIPTION
**Pull request by mcmtroffaes**

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Ready for merge review.

**Comment by pgj** [comment]
Excellent, thanks!

Though, would not have made more sense if you fixed up your commits (`commit --amend`, combined with `rebase`) and re-pushed (`push --force`) the commits?  In my humble opinion, such further fixes add only noise to the commits -- while they could have been just merged into the original ones and proposed again as part of the pull request.  I have done that before here, on GitHub, and it worked well for me.

**Comment by mcmtroffaes** [comment]
Sure - just done that. Is this style of rebasing & squashing commits ok with you now?

**Comment by pgj** [comment]
Of course, that is why I suggested.

**Comment by mcmtroffaes** [comment]
Thanks!

**Pull request merged**
